// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250415164717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StoreApp.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Phone",
                            Description = "Good",
                            Name = "IPhone X",
                            Price = 10000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Phone",
                            Description = "Good",
                            Name = "IPhone 11",
                            Price = 20000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phone",
                            Description = "Good",
                            Name = "IPhone 12",
                            Price = 30000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phone",
                            Description = "Good",
                            Name = "IPhone 13",
                            Price = 40000
                        },
                        new
                        {
                            Id = 5,
                            Category = "Phone",
                            Description = "Good",
                            Name = "IPhone 14",
                            Price = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
